/* empty css                      */import{S as h,A as g}from"./assets/vendor-C_lmVHsc.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();let f=null;function p(){window.innerWidth<1440?f||(f=new h(".my-swiper",{modules:[g],slidesPerView:1.18,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1}})):f&&(f.destroy(!0,!0),f=null)}window.addEventListener("load",p);window.addEventListener("resize",p);document.querySelectorAll(".faq-acc-el-trigger").forEach(c=>{c.addEventListener("click",()=>{const n=c.closest(".faq-acc-el"),l=n.querySelector(".faq-acc-el-descr-frame");n.classList.contains("open")?(n.classList.remove("open"),l.style.maxHeight="0"):(n.classList.add("open"),l.style.maxHeight=l.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),n=c.querySelector(".icon"),l=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 8H17M6 16H17M6 12H17" stroke="#2E3231" stroke-linecap="square" />
</svg>
    `,o=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 8L12 12M12 12L8 16M12 12L16 16M12 12L16 8" stroke="#2E3231" stroke-linecap="square" stroke-linejoin="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,n.innerHTML=t?o:a,t?s():i()}),d.forEach(u=>u.addEventListener("click",()=>{i(),n.innerHTML=a,t=!1})),window.addEventListener("scroll",r);function s(){l.style.display="block"}function i(){l.style.display="none"}function r(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const s=document.getElementById(o);if(!s)return;const i=c(),r=s.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(o=>{o.addEventListener("click",function(s){const i=this.getAttribute("href");if(!i)return;const[r,u]=i.split("#");if(!u)return;const m=window.location.pathname.split("/").pop();!(r===""||r==="./"||r===m||r==="./"+m)||!document.getElementById(u)||(s.preventDefault(),n(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(o){e.forEach(i=>i.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${o}"]`);s&&s.closest(".navigation-item").classList.add("active")}function a(){const o=window.pageYOffset+c()+100;d.forEach(s=>{const i=s.offsetTop,r=i+s.offsetHeight;o>=i&&o<r&&t(s.id)})}if(window.addEventListener("scroll",a),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{n(o),t(o)},300)}});
//# sourceMappingURL=index.js.map
