import{S as h,A as g}from"./assets/vendor-C_lmVHsc.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function l(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function d(e){if(e.ep)return;e.ep=!0;const t=l(e);fetch(e.href,t)}})();let f=null;function p(){window.innerWidth<1440?f||(f=new h(".my-swiper",{modules:[g],slidesPerView:1.18,spaceBetween:16,loop:!0,autoplay:{delay:3e3,disableOnInteraction:!1}})):f&&(f.destroy(!0,!0),f=null)}window.addEventListener("load",p);window.addEventListener("resize",p);document.querySelectorAll(".faq-acc-el-trigger").forEach(c=>{c.addEventListener("click",()=>{const o=c.closest(".faq-acc-el"),l=o.querySelector(".faq-acc-el-descr-frame");o.classList.contains("open")?(o.classList.remove("open"),l.style.maxHeight="0"):(o.classList.add("open"),l.style.maxHeight=l.scrollHeight+"px")})});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),o=c.querySelector(".icon"),l=document.querySelector(".modal"),d=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const a=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M6 8H17M6 16H17M6 12H17" stroke="#2E3231" stroke-linecap="square" />
</svg>
    `,n=`
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 8L12 12M12 12L8 16M12 12L16 16M12 12L16 8" stroke="#2E3231" stroke-linecap="square" stroke-linejoin="round" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,o.innerHTML=t?n:a,t?s():i()}),d.forEach(u=>u.addEventListener("click",()=>{i(),o.innerHTML=a,t=!1})),window.addEventListener("scroll",r);function s(){l.style.display="block"}function i(){l.style.display="none"}function r(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const n=document.getElementById("site-header");return n?n.offsetHeight:0}function o(n){const s=document.getElementById(n);if(!s)return;const i=c(),r=s.getBoundingClientRect().top+window.pageYOffset-i;window.scrollTo({top:r,behavior:"smooth"})}document.querySelectorAll(".navigation-item a").forEach(n=>{n.addEventListener("click",function(s){const i=this.getAttribute("href");if(!i)return;const[r,u]=i.split("#");if(!u)return;const m=window.location.pathname.split("/").pop();!(r===""||r==="./"||r===m||r==="./"+m)||!document.getElementById(u)||(s.preventDefault(),o(u),t(u))})});const d=document.querySelectorAll("section[id]"),e=document.querySelectorAll(".navigation-item");function t(n){e.forEach(i=>i.classList.remove("active"));const s=document.querySelector(`.navigation-item a[href*="#${n}"]`);s&&s.closest(".navigation-item").classList.add("active")}function a(){const n=window.pageYOffset+c()+100;d.forEach(s=>{const i=s.offsetTop,r=i+s.offsetHeight;n>=i&&n<r&&t(s.id)})}if(window.addEventListener("scroll",a),window.location.hash){const n=window.location.hash.substring(1);setTimeout(()=>{o(n),t(n)},300)}});
//# sourceMappingURL=index.js.map
